config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'live_chat#index'
	post '/user_login', to: 'live_chat#create'
	get '/chatting', to: 'live_chat#show'
	mount ActionCable.server => '/chat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/live_chat_controller.rb
class LiveChatController < ApplicationController

	def index
		unless $redis.get(cookies[:user_name]).nil?
			redirect_to chatting_path
		end
	end

	def create
		cookies[:user_name] = params[:user_name]
		unless $redis.get(params[:user_name]).nil?
			redirect_to root_path
		end
		redirect_to chatting_path
	end

	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/live_chat_helper.rb
module LiveChatHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveChat</title>
    <%= csrf_meta_tags %>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/adapterjs/0.14.0/adapter.min.js">

		</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/live_chat/index.html.erb
<%= flash[:error] %>
<h3> Write your Name</h3>
<%= form_tag(user_login_path, method: :post) do %>
	<%= text_field_tag(:user_name, value = nil) %>
	<button type="submit" name="button">Submit </button>
<% end %>

app/views/live_chat/show.html.erb
<%= javascript_include_tag 'chat_handler' %>
<%= javascript_include_tag 'cable'%>
<%= javascript_include_tag 'live_chat'%>
<div id="user_list"> </div>
<h3 id="my_name"></h3>
<video src="" autoplay >

</video>
<video id="remote" src="" autoplay>

</video>